### ISSUE TITLE
Update bridge discovery endpoint (nupnp)

### ISSUE THREAD

**Issue by metonym** [sqmk/huejay#108]
As per the [blog post](https://developers.meethue.com/news/), the https://www.meethue.com/api/nupnp endpoint will be deprecated on July 1, 2019.

**Proposed Change**
In the [`DiscoveryStrategy/Nupnp.js`](https://github.com/sqmk/huejay/blob/master/lib/DiscoveryStrategy/Nupnp.js#L6) file, the Philips nupnp url can be swapped with https://discovery.meethue.com/.

**Comment by garagd** [comment]
Right on. I'll get this change in the next few days.

**Comment by hermanbanken** [comment]
I second this. It will really be deleted soon.

**Comment by sqmk** [comment]
This is now corrected in v1.9.0. Package is available in NPM.
