### ISSUE TITLE
Wrong path to 'Error' in lib/Command/User/Utils.js

### ISSUE THREAD

**Issue by monkybrain** [sqmk/huejay#56]
When trying to create a new user I got an error message saying " Cannot find module '../Error' " so had to manually change the path in `lib/Command/User/Utils.js` from

`let Error = require('../Error')`

to

`let Error = require('../../Error')`

**Comment by sqmk** [comment]
How embarrassing.

I've corrected the issue and published the change in v1.0.2. You should be able to pull the latest update via NPM.

Thanks @monkybrain.

**Comment by monkybrain** [comment]
Great, thanks!
