### ISSUE TITLE
Lights reset to `brightness`=1 after toggling `on`

### ISSUE THREAD

**Issue by WeeJeWel** [sqmk/huejay#70]
Steps to reproduce:

```
// assuming light.brightness == 1
light.on = false
bridge.save()
... wait 1s ...
light.on = true;
// light is dimmed here, after running lights.getAll, it also returns brightness=1
```

My previous library, node-hue-api, didn't have this issue. Maybe it happens when not sending the `bri` property together with the `on` property?

**Comment by sqmk** [comment]
The code sample above isn't telling me much, especially with setting light attributes and using a non-related method to save bridge configuration (`bridge.save()`).

Can you include a complete code sample with sample output that shows this entire behavior you are experiencing?

**Comment by WeeJeWel** [comment]
Hm sorry about the `bridge.save()`, should've been `light.save()`. However I cannot seem to reproduce the issue anymore. This might've been a bug on the Bridge itself, it did update recently.

If it re-occurs, I'll provide a working example :-)

**Comment by WeeJeWel** [comment]
Haha, just after I closed the issue I figured that I actually did change something in my code.

I literally did the following:

old:

```
light.on = false;
client.lights.save( light );
...
light.on = true;
client.lights.save( light );
```

new:

```
light.on = false;
light.brightness = light.brightness;
client.lights.save( light );
...
light.on = true;
light.brightness = light.brightness;
client.lights.save( light );
```

In the old example, the light dims to minimum brightness after toggling on again. In the new example, everything works as expected.

Without knowing too much about the inner workings of huejay, I suspect that after a brightness set, the Hue API command includes the brightness (`bri` property). I assume that if it doesn't, the lights is reset to lowest brightness state.

I'm not sure whether this is expected behavior or not. It seems odd for the bridge to automatically dim the light after turning it back on again, because the official Android app doesn't seem to have that behavior either. However, using this approach, the settings is overwritten if another client is used simultaniously.

**Comment by sqmk** [comment]
Huejay will only send attributes that have changed to the bridge to help with performance.

What I can do is allow for providing a second argument accepting an array of properties for force saving to the bridge (even if they haven't changed).

Example:
```js
// Force saving/updating brightness 
client.lights.save(light, ['brightness', 'on']);
```

Would this work for you?

**Comment by WeeJeWel** [comment]
Well, I've got a workaround that works for me (light.brightness = light.brightness), but this might be something you want to look into / think somewhat longer about :-)

In case you find it 'correct' behavior, please close the issue!
