### ISSUE TITLE
[request] Is it possibe to emulate a new bulb?

### ISSUE THREAD

**Issue by KyleTryon** [sqmk/huejay#86]
I have been looking for a solution to build my own lights and integrate them with Hue. IS there any way to use this npm to create a "bridge" between a light of my design and the hue system. I could theoretically use this control my lights based on the rest of Hue theoretically but that isnt really the desired effect I am looking for. I would like to have my lights show up in the app.

**Comment by sqmk** [comment]
This library is used for controlling lights via the Philips Hue bridge. If the bridge supports lights of your own design, you can use this library to control them. However, if the interface is different for your custom light that isn't friendly to Hue's system, this library should not manage them. I don't have plans on making this library support any other light system.
